language: node_js
node_js:
    - "6"
    - "4"

os:
    - osx

sudo: required

install:
    - npm install

before_script:
    - chmod +x /Users/travis/build/codearoni/zxp-sign-cmd/bin/

script:
    - npm run test-ci

after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
