language: node_js
node_js:
    - "6"
    - "4"

os:
    - osx

install:
    - npm install -g npm@latest
    - npm install

before_script:
    - chmod -R a+x .

script:
    - npm run test-ci

after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
