language: node_js
sudo: true
node_js:
    - "6"
    - "4"

os:
    - osx

install:
    - npm install -g npm@latest
    - npm install

before_script:
    - mkdir -p ./bin
    - chmod a+x ./bin
    - chmod a+x ./node_modules/zxp-provider/bin/osx/ZXPSignCmd

script:
    - npm run test-ci

after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
